INSERT INTO mydb.Country (country_name) VALUES ("Argentina");
INSERT INTO mydb.Country (country_name) VALUES ("Brazil");
INSERT INTO mydb.Country (country_name) VALUES ("USA");
INSERT INTO mydb.Country (country_name) VALUES ("Chile");
INSERT INTO mydb.Country (country_name) VALUES ("Uruguay");
INSERT INTO mydb.Country (country_name) VALUES ("Peru");
INSERT INTO mydb.Country (country_name) VALUES ("Bolivia");
INSERT INTO mydb.Country (country_name) VALUES ("Ecuador");
INSERT INTO mydb.Country (country_name) VALUES ("Colombia");
INSERT INTO mydb.Country (country_name) VALUES ("Venezuela");
INSERT INTO mydb.Country (country_name) VALUES ("Mexico");
INSERT INTO mydb.Country (country_name) VALUES ("Canada");
INSERT INTO mydb.Country (country_name) VALUES ("Costa Rica");
INSERT INTO mydb.Country (country_name) VALUES ("Cuba");
INSERT INTO mydb.Country (country_name) VALUES ("Puerto Rico");
SELECT * FROM mydb.Country;