-- MySQL Script generated by MySQL Workbench
-- Wed Aug  4 17:20:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BookingSuarez
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BookingSuarez` ;

-- -----------------------------------------------------
-- Schema BookingSuarez
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BookingSuarez` DEFAULT CHARACTER SET utf8 ;
USE `BookingSuarez` ;

-- -----------------------------------------------------
-- Table `BookingSuarez`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`Country` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`Country` (
  `idCountry` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`City` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(128) NULL,
  `postal_code` VARCHAR(16) NULL,
  `Country_idCountry` INT NOT NULL,
  PRIMARY KEY (`idCity`),
  INDEX `fk_City_Country1_idx` (`Country_idCountry` ASC) ,
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `BookingSuarez`.`Country` (`idCountry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`Travel_Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`Travel_Company` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`Travel_Company` (
  `idTravelCompany` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `City_idCity` INT NOT NULL,
  PRIMARY KEY (`idTravelCompany`, `City_idCity`),
  INDEX `fk_Travel_Company_City1_idx` (`City_idCity` ASC) ,
  CONSTRAINT `fk_Travel_Company_City1`
    FOREIGN KEY (`City_idCity`)
    REFERENCES `BookingSuarez`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`Plane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`Plane` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`Plane` (
  `idPlane` INT NOT NULL AUTO_INCREMENT,
  `capacity` DECIMAL(10,2) NOT NULL,
  `Travel_Company_idTravelCompany` INT NOT NULL,
  `Travel_Company_City_idCity` INT NOT NULL,
  PRIMARY KEY (`idPlane`),
  INDEX `fk_Plane_Travel_Company1_idx` (`Travel_Company_idTravelCompany` ASC, `Travel_Company_City_idCity` ASC) ,
  CONSTRAINT `fk_Plane_Travel_Company1`
    FOREIGN KEY (`Travel_Company_idTravelCompany` , `Travel_Company_City_idCity`)
    REFERENCES `BookingSuarez`.`Travel_Company` (`idTravelCompany` , `City_idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`Hotel` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`Hotel` (
  `idHotel` INT NOT NULL AUTO_INCREMENT,
  `hotel_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `City_idCity` INT NOT NULL,
  `Travel_Company_idTravelCompany` INT NULL,
  `Travel_Company_City_idCity` INT NULL,
  PRIMARY KEY (`idHotel`),
  INDEX `fk_Hotel_City1_idx` (`City_idCity` ASC) ,
  INDEX `fk_Hotel_Travel_Company1_idx` (`Travel_Company_idTravelCompany` ASC, `Travel_Company_City_idCity` ASC) ,
  CONSTRAINT `fk_Hotel_City1`
    FOREIGN KEY (`City_idCity`)
    REFERENCES `BookingSuarez`.`City` (`idCity`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Hotel_Travel_Company1`
    FOREIGN KEY (`Travel_Company_idTravelCompany` , `Travel_Company_City_idCity`)
    REFERENCES `BookingSuarez`.`Travel_Company` (`idTravelCompany` , `City_idCity`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`Room` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`Room` (
  `idRoom` INT NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `current_price` INT NULL,
  `Hotel_idHotel` INT NOT NULL,
  PRIMARY KEY (`idRoom`),
  INDEX `fk_Room_Hotel1_idx` (`Hotel_idHotel` ASC) ,
  CONSTRAINT `fk_Room_Hotel1`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `BookingSuarez`.`Hotel` (`idHotel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`User` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(128) NULL,
  `last_name` VARCHAR(128) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `details` TEXT(255) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`Reservation` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`Reservation` (
  `idReservation` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `discount` DECIMAL(5,2) NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idReservation`, `User_idUser`),
  INDEX `fk_Reservation_User1_idx` (`User_idUser` ASC) ,
  CONSTRAINT `fk_Reservation_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `BookingSuarez`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`Room_Reserved`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`Room_Reserved` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`Room_Reserved` (
  `idRoom_Reserved` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(10,2) NULL,
  `Room_idRoom` INT NOT NULL,
  `Reservation_idReservation` INT NOT NULL,
  PRIMARY KEY (`idRoom_Reserved`),
  INDEX `fk_Room_Reserved_Room1_idx` (`Room_idRoom` ASC) ,
  INDEX `fk_Room_Reserved_Reservation1_idx` (`Reservation_idReservation` ASC) ,
  CONSTRAINT `fk_Room_Reserved_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `BookingSuarez`.`Room` (`idRoom`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Room_Reserved_Reservation1`
    FOREIGN KEY (`Reservation_idReservation`)
    REFERENCES `BookingSuarez`.`Reservation` (`idReservation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`User_Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`User_Account` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`User_Account` (
  `idUser_Account` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `Travel_Company_idTravelCompany` INT NOT NULL,
  PRIMARY KEY (`idUser_Account`),
  INDEX `fk_User_Account_Travel_Company1_idx` (`Travel_Company_idTravelCompany` ASC) ,
  CONSTRAINT `fk_User_Account_Travel_Company1`
    FOREIGN KEY (`Travel_Company_idTravelCompany`)
    REFERENCES `BookingSuarez`.`Travel_Company` (`idTravelCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`plan` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`plan` (
  `idplan` INT NOT NULL AUTO_INCREMENT,
  `plan_name` VARCHAR(255) NOT NULL,
  `details` VARCHAR(255) NULL,
  `max_room` INT NOT NULL,
  `min_room` INT NULL,
  `monthly_price` INT NOT NULL,
  PRIMARY KEY (`idplan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookingSuarez`.`company_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookingSuarez`.`company_plan` ;

CREATE TABLE IF NOT EXISTS `BookingSuarez`.`company_plan` (
  `idCompany_plan` INT NOT NULL AUTO_INCREMENT,
  `plan_idplan` INT NOT NULL,
  `Travel_Company_idTravelCompany` INT NOT NULL,
  PRIMARY KEY (`idCompany_plan`),
  INDEX `fk_company_plan_plan_idx` (`plan_idplan` ASC) ,
  INDEX `fk_company_plan_Travel_Company1_idx` (`Travel_Company_idTravelCompany` ASC) ,
  CONSTRAINT `fk_company_plan_plan`
    FOREIGN KEY (`plan_idplan`)
    REFERENCES `BookingSuarez`.`plan` (`idplan`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_company_plan_Travel_Company1`
    FOREIGN KEY (`Travel_Company_idTravelCompany`)
    REFERENCES `BookingSuarez`.`Travel_Company` (`idTravelCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ----------------TABLE INSERTION-------------------
			
-- ----------------COUNTRY---------------------------

INSERT INTO BookingSuarez.Country (country_name) VALUES ("Argentina");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Brazil");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("USA");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Chile");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Uruguay");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Peru");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Bolivia");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Ecuador");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Colombia");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Venezuela");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Mexico");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Canada");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Costa Rica");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Cuba");
INSERT INTO BookingSuarez.Country (country_name) VALUES ("Puerto Rico");

-- ----------------CITY---------------------------

INSERT INTO BookingSuarez.City (city_name, postal_code, Country_idCountry) VALUES
("Necochea", 7630, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Argentina")),
("Quequen", 7631, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Argentina")),
("Rio de Janeiro", 22050000, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Brazil")),
("Brazilia", 70040, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Brazil")),
("Miami", 33101, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "USA")),
("Los Angeles", 90001, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "USA")),
("Santiago de Chile", 1030000, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Chile")),
("Montevideo", 10129, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Uruguay")),
("Lima", 07001, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Peru")),
("Bogota", 110111, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Colombia")),
("La Paz", 02010220, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Bolivia")),
("Quito", 170102, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Ecuador")),
("Caracas", 1000, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Venezuela")),
("Mexico DC", 00810, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Mexico")),
("Ottawa", 19441, (SELECT idCountry FROM BookingSuarez.Country WHERE country_name = "Canada"));

-- ----------------HOTEL---------------------------

INSERT INTO BookingSuarez.Hotel (hotel_name, City_idCity) VALUES
("Hotel Niken", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Necochea")),
("Hotel Real", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Necochea")),
("Hotel Rio de Janeiro", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Rio de Janeiro")),
("Hotel Brazilia", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Brazilia")),
("Hotel Miami", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Miami")),
("Hotel Los Angeles", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Los Angeles")),
("Hotel Santiago de Chile", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Santiago de Chile")),
("Hotel Montevideo", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Montevideo")),
("Hotel Lima", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Lima")),
("Hotel Bogota", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Bogota")),
("Hotel La Paz", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "La Paz")),
("Hotel Quito", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Quito")),
("Hotel Caracas", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Caracas")),
("Hotel Mexico DC", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Mexico DC")),
("Hotel Ottawa", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Ottawa"));


-- ----------------ROOM---------------------------

INSERT INTO BookingSuarez.Room (room_name, current_price, Hotel_idHotel) VALUES
    ( "Niken Single", 100, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Niken")), 
    ( "Niken Double", 200, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Niken")),
    ( "Real Triple", 300, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Real")),
    ( "Real Quad", 400, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Real")),
    ( "Rio de Janeiro Queen", 500, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Rio de Janeiro")),
    ( "Rio de Janeiro King", 600, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Rio de Janeiro")),
    ( "Brazilia Double-double", 700, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Brazilia")),
    ( "Brazilia Suite", 800, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Brazilia")),
    ( "Miami Executive Suite", 900, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Miami")),
    ( "Miami Presidential Suite",1000, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Miami")),
    ( "LA Apartment", 1100, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Los Angeles")),
    ( "LA Cabin", 1200, (SELECT idHotel FROM BookingSuarez.Hotel WHERE hotel_name= "Hotel Los Angeles"));

-- ----------------USER---------------------------

INSERT INTO BookingSuarez.User (first_name, last_name, email, phone, address) VALUES 
("Gonzalo", "Suarez", "legonza424@gmail.com", 2262651853, "521 street, number 344"),
("Mariano", "Suarez", "lemariano424@gmail.com", 213124125, "421 street, number 425"),
("Richard", "Rogers", "rrogers@gmail.com", 214252141242, "421 street, number 5125"),
("Marrie", "Anne", "manne@gmail.com", 241451243, "12 street, number 21412"),
("Angel", "Di Maria", "adimaria@gmail.com", 41251241, "5123 street, number 12314"),
("Lionel", "Messi", "lmessi@gmail.com", 10101010, "10 street, number 10"),
("Rodrigo", "De Paul", "rdepaul@gmail.com", 88888888, "88 street, number 888"),
("Emiliano", "Martinez", "emartinez@gmail.com", 2141412, "1 street, number 1"),
("Lautaro", "Martinez", "lmartinez@gmail.com", 2142143, "124 street, number 999"),
("Leandro", "Paredes", "lparedes@gmail.com", 124121251, "5 street, number 555"),
("Giovani", "Lo Celso", "glocelso@gmail.com", 12451231, "64 street, number 344"),
("Nicolas", "Otamendi", "notamendi@gmail.com", 098765424, "67 street, number 25644"),
("Gonzalo", "Montiel", "gmontiel@gmail.com", 124512265, "765 street, number 3333"),
("Cristian", "Romero", "cromero@gmail.com", 98756782, "512 street, number 51441"),
("Marcos", "Acuna", "macuna@gmail.com", 22626518533, "521 street, number 344");

-- ----------------RESERVATION---------------------------

INSERT INTO BookingSuarez.Reservation (start_date, total_price, User_idUser) VALUES
(STR_TO_DATE("10,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Gonzalo" and last_name = "Suarez")), 
(STR_TO_DATE("9,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Gonzalo" and last_name = "Montiel")), 
(STR_TO_DATE("8,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Lionel" and last_name = "Messi")), 
(STR_TO_DATE("7,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Angel" and last_name = "Di Maria")), 
(STR_TO_DATE("6,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Giovani" and last_name = "Lo Celso")), 
(STR_TO_DATE("5,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Nicolas" and last_name = "Otamendi")), 
(STR_TO_DATE("4,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Mariano" and last_name = "Suarez")), 
(STR_TO_DATE("3,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Lautaro" and last_name = "Martinez")), 
(STR_TO_DATE("2,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Emiliano" and last_name = "Martinez")), 
(STR_TO_DATE("1,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Leandro" and last_name = "Paredes")), 
(STR_TO_DATE("11,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Cristian" and last_name = "Romero")), 
(STR_TO_DATE("12,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Marcos" and last_name = "Acuna")), 
(STR_TO_DATE("13,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Richard" and last_name = "Rogers")), 
(STR_TO_DATE("14,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Marrie" and last_name = "Anne")),
(STR_TO_DATE("14,7,2021", "%d,%m,%Y"), 1000, (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Rodrigo" and last_name = "De Paul"));

-- ----------------PLAN---------------------------

INSERT INTO BookingSuarez.plan(plan_name, max_room, monthly_price) VALUES
("Summer Discount", 8, 500),
("Winter Discount", 4, 800),
("Chistmas Discount", 5, 700),
("New Year Discount", 5, 400),
("Easters Discount", 5, 650),
("Spring Discount", 4, 350),
("Autum Discount", 2, 600),
("Thanks Giving Discount", 5, 500),
("Holiday Discount", 2, 350);

-- ----------------TRAVEL_COMPANY---------------------------

INSERT INTO BookingSuarez.Travel_Company(company_name, City_idCity) VALUES
("Travel Solvd", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Necochea")),
("Travel Quequen", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Quequen")),
("Travel Rio", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Rio de Janeiro")),
("Travel Brazilia", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Brazilia")),
("Travel Miami", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Miami")),
("Travel LA", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Los Angeles")),
("Travel Montevideo", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Montevideo")),
("Travel Bogota", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Bogota")),
("Travel Lima", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Lima")),
("Travel Caracas", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Caracas")),
("Travel Chile", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Santiago de Chile")),
("Travel Ottawa", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Ottawa")),
("Travel Mexico", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Mexico DC")),
("Travel Paz", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "La Paz")),
("Travel Quito", (SELECT idCity FROM BookingSuarez.City WHERE city_name= "Quito"));

-- ----------------USER_ACCOUNT---------------------------

INSERT INTO BookingSuarez.User_Account(first_name, user_name, password, Travel_Company_idTravelCompany) VALUES
("Gonzalo", "GonzaSuarez", "password", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Solvd")),
("Mariano", "MSuarez", "password", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Quequen")),
("Richard", "RRogers", "password", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Rio")),
("Marrie", "Anne", "MAnne", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Brazilia")),
("Angel", "Di Maria", "ADMaria", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Miami")),
("Lionel", "Messi", "TheGOAT", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Montevideo")),
("Rodrigo", "De Paul", "RDPaul", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Bogota")),
("Emiliano", "Martinez", "EMartinez", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Lima")),
("Lautaro", "Martinez", "LMartinez", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Caracas")),
("Leandro", "Paredes", "LParedes", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Chile")),
("Giovani", "Lo Celso", "GLCelso", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Ottawa")),
("Nicolas", "Otamendi", "NOtamendi", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Mexico")),
("Gonzalo", "Montiel", "GMontiel", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Paz")),
("Cristian", "Romero", "CRomero", (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Quito"));

-- ----------------COMPANY_PLANS---------------------------

INSERT INTO BookingSuarez.company_plan (plan_idplan, Travel_Company_idTravelCompany) VALUES
((SELECT idplan FROM BookingSuarez.plan WHERE plan_name= "Summer Discount"),(SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Solvd")),
((SELECT idplan FROM BookingSuarez.plan WHERE plan_name= "Winter Discount"),(SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Quequen")),
((SELECT idplan FROM BookingSuarez.plan WHERE plan_name= "Easters Discount"),(SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Quequen")),
((SELECT idplan FROM BookingSuarez.plan WHERE plan_name= "New Year Discount"),(SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Solvd")),
((SELECT idplan FROM BookingSuarez.plan WHERE plan_name= "Chistmas Discount"),(SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Miami")),
((SELECT idplan FROM BookingSuarez.plan WHERE plan_name= "Autum Discount"),(SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Miami")),
((SELECT idplan FROM BookingSuarez.plan WHERE plan_name= "Spring Discount"),(SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel LA")),
((SELECT idplan FROM BookingSuarez.plan WHERE plan_name= "Holiday Discount"),(SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel LA")),
((SELECT idplan FROM BookingSuarez.plan WHERE plan_name= "Thanks Giving Discount"),(SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel LA"));

-- ----------------PLANE---------------------------

INSERT INTO BookingSuarez.Plane(capacity,Travel_Company_idTravelCompany, Travel_Company_City_idCity) VALUES
(200, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Solvd"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Solvd")),
(300, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Solvd"),(SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Solvd")),
(200, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Quequen"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Quequen")),
(300, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Quequen"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Quequen")),
(200, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Miami"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Miami")),
(300, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Miami"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Miami")),
(200, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel LA"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel LA")),
(300, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel LA"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel LA")),
(200, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Brazilia"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Brazilia")),
(300, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Brazilia"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Brazilia")),
(200, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Montevideo"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Montevideo")),
(300, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Montevideo"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Montevideo")),
(200, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Ottawa"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Ottawa")),
(200, (SELECT idTravelCompany FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Ottawa"), (SELECT City_idCity FROM BookingSuarez.Travel_Company WHERE company_name = "Travel Ottawa"));

-- ----------------ROOM_RESERVED---------------------------

INSERT INTO BookingSuarez.Room_Reserved(Room_idRoom,Reservation_idReservation) VALUE
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Niken Single") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Gonzalo" and last_name = "Suarez"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Niken Double") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Gonzalo" and last_name = "Montiel"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Miami Presidential Suite") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Lionel" and last_name = "Messi"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Real Triple") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Lautaro" and last_name = "Martinez"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Real Quad") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Angel" and last_name = "Di Maria"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Rio de Janeiro Queen") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Emiliano" and last_name = "Martinez"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Rio de Janeiro King") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Giovani" and last_name = "Lo Celso"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Brazilia Double-double") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Nicolas" and last_name = "Otamendi"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Brazilia Suite") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Rodrigo" and last_name = "De Paul"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Niken Single") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Leandro" and last_name = "Paredes"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Niken Single") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Mariano" and last_name = "Suarez"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Niken Double") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Cristian" and last_name = "Romero"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Real Triple") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Marcos" and last_name = "Acuna"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="Real Quad") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Richard" and last_name = "Rogers"))),
((SELECT idRoom FROM BookingSuarez.Room WHERE room_name="LA Cabin") , (SELECT idReservation FROM BookingSuarez.Reservation WHERE User_idUser = (SELECT idUser FROM BookingSuarez.User WHERE first_name = "Marrie" and last_name = "Anne")));

-- -----------------------------------------------------------